<?php

/**
  * Implements hook_ctools_plugin_directory().
  */
 function labels_ctools_plugin_directory($module, $plugin) {
   if ($module == 'ctools' && $plugin == 'export_ui') {
     return "plugins/$plugin";
   }
 }

/**
 * Load a fully-loaded label object.
 * @param $name
 *   The machine-name of the label.
 */
function labels_load($name) {
  ctools_include('export');
  return ctools_export_crud_load('labels', $name);
}

/**
 * Load all the things!
 */
function labels_load_all() {
  ctools_include('export');
  return ctools_export_crud_load_all('labels');
}
